# Generated by Django 6.0 on 2025-12-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaNarrative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_text", models.TextField()),
                ("posting_time", models.DateTimeField(null=True)),
                ("media_outlet", models.CharField(max_length=255)),
                ("inferred_actor", models.CharField(max_length=255, null=True)),
                ("strategic_intent", models.CharField(max_length=255, null=True)),
                ("strategic_intent_id", models.IntegerField(null=True)),
                ("sector", models.CharField(max_length=255)),
                ("tone", models.FloatField(null=True)),
                ("target_country", models.CharField(max_length=255)),
                ("url", models.URLField(unique=True)),
                ("confidence", models.FloatField(null=True)),
                ("lang_detect", models.CharField(max_length=50)),
                ("use_afrolm", models.BooleanField(default=False)),
                ("llm_strat", models.CharField(max_length=255, null=True)),
                ("llm_strat_conf", models.FloatField(null=True)),
                ("llm_strat_notes", models.TextField(null=True)),
                ("pseudo_kept", models.BooleanField(default=False)),
                ("pseudo_weight", models.FloatField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
