# Generated by Django 6.0 on 2025-12-29 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medianarrative",
            options={"ordering": ["-posting_time"]},
        ),
        migrations.RemoveField(
            model_name="medianarrative",
            name="created_at",
        ),
        migrations.AddField(
            model_name="medianarrative",
            name="llm_strat_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="medianarrative",
            name="confidence",
            field=models.FloatField(default=4.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="medianarrative",
            name="inferred_actor",
            field=models.CharField(default="Unknown", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="medianarrative",
            name="lang_detect",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="medianarrative",
            name="llm_strat",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="medianarrative",
            name="llm_strat_conf",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="medianarrative",
            name="llm_strat_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="medianarrative",
            name="posting_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 12, 29, 8, 50, 11, 48433, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="medianarrative",
            name="pseudo_kept",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="medianarrative",
            name="pseudo_weight",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="medianarrative",
            name="strategic_intent",
            field=models.CharField(default="Unknown", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="medianarrative",
            name="strategic_intent_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="medianarrative",
            name="tone",
            field=models.CharField(default="Unknown", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="medianarrative",
            name="url",
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name="medianarrative",
            name="use_afrolm",
            field=models.BooleanField(),
        ),
    ]
