# Generated by Django 6.0 on 2025-12-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_medianarrative_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medianarrative",
            name="author",
            field=models.CharField(
                blank=True, default="Unknown", max_length=255, null=True
            ),
        ),
    ]
