# Generated by Django 6.0 on 2026-01-01 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_medianarrative_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Journalist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "country_based",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("linkedin_profile", models.URLField(blank=True, null=True)),
                ("facebook_profile", models.URLField(blank=True, null=True)),
                ("x_profile", models.URLField(blank=True, null=True)),
                ("instagram_profile", models.URLField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MediaOutlet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "parent_organisation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("content_sharing_agreements", models.TextField(blank=True, null=True)),
                ("linkedin_profile", models.URLField(blank=True, null=True)),
                ("facebook_profile", models.URLField(blank=True, null=True)),
                ("x_profile", models.URLField(blank=True, null=True)),
                ("instagram_profile", models.URLField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="medianarrative",
            options={},
        ),
        migrations.RemoveField(
            model_name="medianarrative",
            name="article_text",
        ),
        migrations.RemoveField(
            model_name="medianarrative",
            name="confidence",
        ),
        migrations.RemoveField(
            model_name="medianarrative",
            name="inferred_actor",
        ),
        migrations.RemoveField(
            model_name="medianarrative",
            name="lang_detect",
        ),
        migrations.RemoveField(
            model_name="medianarrative",
            name="llm_strat",
        ),
        migrations.RemoveField(
            model_name="medianarrative",
            name="llm_strat_conf",
        ),
        migrations.RemoveField(
            model_name="medianarrative",
            name="llm_strat_id",
        ),
        migrations.RemoveField(
            model_name="medianarrative",
            name="llm_strat_notes",
        ),
        migrations.RemoveField(
            model_name="medianarrative",
            name="posting_time",
        ),
        migrations.RemoveField(
            model_name="medianarrative",
            name="pseudo_kept",
        ),
        migrations.RemoveField(
            model_name="medianarrative",
            name="pseudo_weight",
        ),
        migrations.RemoveField(
            model_name="medianarrative",
            name="sector",
        ),
        migrations.RemoveField(
            model_name="medianarrative",
            name="strategic_intent",
        ),
        migrations.RemoveField(
            model_name="medianarrative",
            name="strategic_intent_id",
        ),
        migrations.RemoveField(
            model_name="medianarrative",
            name="target_country",
        ),
        migrations.RemoveField(
            model_name="medianarrative",
            name="tone",
        ),
        migrations.RemoveField(
            model_name="medianarrative",
            name="url",
        ),
        migrations.RemoveField(
            model_name="medianarrative",
            name="use_afrolm",
        ),
        migrations.AlterField(
            model_name="medianarrative",
            name="author",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="medianarrative",
            name="media_outlet",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="medianarrative",
            name="journalist_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="dashboard.journalist",
            ),
        ),
        migrations.AddField(
            model_name="medianarrative",
            name="media_outlet_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="dashboard.mediaoutlet",
            ),
        ),
    ]
