# Generated by Django 6.0 on 2026-01-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0004_journalist_mediaoutlet_alter_medianarrative_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medianarrative",
            options={
                "ordering": ["-posting_time"],
                "verbose_name": "Media Narrative",
                "verbose_name_plural": "Media Narratives",
            },
        ),
        migrations.AddField(
            model_name="medianarrative",
            name="article_text",
            field=models.TextField(default=" "),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medianarrative",
            name="confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medianarrative",
            name="inferred_actor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="medianarrative",
            name="lang_detect",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="medianarrative",
            name="llm_strat",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="medianarrative",
            name="llm_strat_conf",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medianarrative",
            name="llm_strat_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medianarrative",
            name="llm_strat_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medianarrative",
            name="posting_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medianarrative",
            name="pseudo_kept",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="medianarrative",
            name="pseudo_weight",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="medianarrative",
            name="sector",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="medianarrative",
            name="strategic_intent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="medianarrative",
            name="strategic_intent_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medianarrative",
            name="target_country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="medianarrative",
            name="tone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="medianarrative",
            name="url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="medianarrative",
            name="use_afrolm",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="medianarrative",
            name="author",
            field=models.CharField(
                blank=True, default="Unknown", max_length=255, null=True
            ),
        ),
    ]
