# Generated by Django 4.2.7 on 2026-03-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_medianarrative_vulnerability_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='medianarrative',
            name='ml_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
